/* Generated by configure */
#if __STDC_VERSION__ >= 199901L
// Compiler claims to support C99, trust it
#else
#  error __STDC_VERSION__ must be >= 199901L
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    /* END TEST */
    return 0;
}
