/* Generated by configure */
#include <fontconfig/fontconfig.h>
#ifndef FC_RGBA_UNKNOWN
#  error This version of fontconfig is too old, it is missing the FC_RGBA_UNKNOWN define
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    FcPattern *pattern = 0;
    /* END TEST */
    return 0;
}
