/* Generated by configure */
#include <sys/auxv.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    (void) getauxval(AT_NULL);
    /* END TEST */
    return 0;
}
