/* Generated by configure */
#include <sys/types.h>
#include <sys/socket.h>
#include <net/if.h>
#include <ifaddrs.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    ifaddrs *list;
    getifaddrs(&list);
    freeifaddrs(list);
    /* END TEST */
    return 0;
}
