/* Generated by configure */
#define _ATFILE_SOURCE 1
#include <fcntl.h>
#include <stdio.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    renameat2(AT_FDCWD, argv[1], AT_FDCWD, argv[2], RENAME_NOREPLACE | RENAME_WHITEOUT);
    /* END TEST */
    return 0;
}
