/* Generated by configure */
#include <xkbcommon/xkbcommon.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    xkb_context_new(XKB_CONTEXT_NO_FLAGS);
    /* END TEST */
    return 0;
}
