/* Generated by configure */
#if defined(__GNUC__)
__attribute((visibility("default")))
#elif defined(__SUNPRO_CC)
__global
#else
#  error GCC4+ or SunStudio 8+ are required to support ELF visibility
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    /* END TEST */
    return 0;
}
