/* Generated by configure */
typedef struct _GMainContext GMainContext;
#include <glib.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    g_thread_init(NULL);
    (void) g_main_context_default();
    (void) g_source_new(0, 0);
    g_source_add_poll(NULL, NULL);
    /* END TEST */
    return 0;
}
