/* Generated by configure */
#if __STDC_VERSION__ >= 201112L
// Compiler claims to support C11, trust it
#else
#  error __STDC_VERSION__ must be >= 201112L
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    /* END TEST */
    return 0;
}
