/* Generated by configure */
#include <libpq-fe.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    PQescapeBytea(0, 0, 0);
    PQunescapeBytea(0, 0);
    /* END TEST */
    return 0;
}
