/* Generated by configure */
#include <unistd.h>
#include <time.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    #if defined(_POSIX_MONOTONIC_CLOCK) && (_POSIX_MONOTONIC_CLOCK-0 >= 0)
    timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    #else
    #  error Feature _POSIX_MONOTONIC_CLOCK not available
    #endif
    /* END TEST */
    return 0;
}
