/* Generated by configure */
// Check if EGL is compatible with X. Some EGL implementations, typically on
// embedded devices, are not intended to be used together with X. EGL support
// has to be disabled in plugins like xcb in this case since the native display,
// window and pixmap types will be different than what an X-based platform
// plugin would expect.
#include <EGL/egl.h>
#include <X11/Xlib.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    Display *dpy = EGL_DEFAULT_DISPLAY;
    EGLNativeDisplayType egldpy = XOpenDisplay("");
    dpy = egldpy;
    EGLNativeWindowType w = XCreateWindow(dpy, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
    XDestroyWindow(dpy, w);
    XCloseDisplay(dpy);
    /* END TEST */
    return 0;
}
