/* Generated by configure */
#include <stdlib.h>
#include <stdint.h>
extern "C" {
#include <xf86drmMode.h>
#include <xf86drm.h>
}
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    drmModeAtomicReq *request;
    /* END TEST */
    return 0;
}
