/* Generated by configure */
#include <X11/Xlib-xcb.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    (void) XGetXCBConnection((Display *)0);
    /* END TEST */
    return 0;
}
