/* Generated by configure */
#include <unistd.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    char buf[32];
    (void) getentropy(buf, sizeof(buf));
    /* END TEST */
    return 0;
}
