/* Generated by configure */
#include <harfbuzz/hb.h>
#if !HB_VERSION_ATLEAST(1, 6, 0)
#  error This version of harfbuzz is too old.
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    hb_buffer_t *buffer = hb_buffer_create();
    const uint16_t string[] = { 'A', 'b', 'c' };
    hb_buffer_add_utf16(buffer, string, 3, 0, 3);
    hb_buffer_guess_segment_properties(buffer);
    hb_buffer_set_flags(buffer, hb_buffer_flags_t(HB_BUFFER_FLAG_PRESERVE_DEFAULT_IGNORABLES));
    hb_buffer_destroy(buffer);
    /* END TEST */
    return 0;
}
