/* Generated by configure */
#include <sys/inotify.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    inotify_init();
    inotify_add_watch(0, "foobar", IN_ACCESS);
    inotify_rm_watch(0, 1);
    /* END TEST */
    return 0;
}
