/* Generated by configure */
#include <future>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    std::future<int> f = std::async([]() { return 42; });
    (void)f.get();
    /* END TEST */
    return 0;
}
