/* Generated by configure */
#include <dbus/dbus.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    (void) dbus_bus_get_private(DBUS_BUS_SYSTEM, (DBusError *)NULL);
    /* END TEST */
    return 0;
}
