/* Generated by configure */
#include <fcntl.h>
#include <unistd.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    (void) posix_fallocate(0, 0, 0);
    /* END TEST */
    return 0;
}
