/* Generated by configure */
#include <png.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    (void) png_create_read_struct(PNG_LIBPNG_VER_STRING,0,0,0);
    /* END TEST */
    return 0;
}
