/* Generated by configure */
#include <unistd.h>
#include <time.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    timespec ts; clock_gettime(CLOCK_REALTIME, &ts);
    /* END TEST */
    return 0;
}
