/* Generated by configure */
#include <dlfcn.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    dlclose(dlopen(0, 0));
    dlsym(RTLD_DEFAULT, 0);
    dlerror();
    /* END TEST */
    return 0;
}
