/* Generated by configure */
#include <EGL/egl.h>
#include <EGL/eglvivante.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    #ifdef __INTEGRITY
    fbGetDisplay();
    #else
    // Do not rely on fbGetDisplay(), since the signature has changed over time.
    // Stick to fbGetDisplayByIndex().
    fbGetDisplayByIndex(0);
    #endif
    /* END TEST */
    return 0;
}
