/* Generated by configure */
#include <EGL/egl.h>
#include <EGL/eglext.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    EGLDeviceEXT device = 0;
    EGLStreamKHR stream = 0;
    EGLOutputLayerEXT layer = 0;
    (void) EGL_DRM_CRTC_EXT;
    /* END TEST */
    return 0;
}
