/* Generated by configure */
#include <X11/extensions/Xrender.h>
#if RENDER_MAJOR == 0 && RENDER_MINOR < 5
#  error Required Xrender version 0.6 not found.
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    XRenderPictFormat *format = 0;
    /* END TEST */
    return 0;
}
