/* Generated by configure */
#include <iconv.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    iconv_t x = iconv_open("", "");
    char *inp, *outp;
    size_t inbytes, outbytes;
    iconv(x, &inp, &inbytes, &outp, &outbytes);
    iconv_close(x);
    /* END TEST */
    return 0;
}
