/* Generated by configure */
#include <EGL/egl.h>
#include <GLES2/gl2.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    mali_native_window *w = 0;
    /* END TEST */
    return 0;
}
